# Generated by Django 5.2.8 on 2026-01-14 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('borrower_name', models.CharField(blank=True, max_length=255)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_file_name', models.CharField(max_length=255)),
                ('executed_file', models.FileField(blank=True, null=True, upload_to='documents/executed/')),
                ('term_sheet_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('term_sheet_file', models.FileField(blank=True, null=True, upload_to='documents/termsheets/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('HIGH', 'High')], max_length=10)),
                ('code', models.CharField(choices=[('MISMATCH', 'Mismatch'), ('MULTIPLE_VALUES', 'Multiple Values'), ('MISSING_CLAUSE', 'Missing Clause'), ('CONSISTENCY_FAIL', 'Consistency Failure')], max_length=30)),
                ('message', models.TextField()),
                ('related_term_label', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence', models.TextField()),
                ('regulation_impact', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reviews.review')),
            ],
            options={
                'ordering': ['-severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('source', models.CharField(choices=[('EXECUTED', 'Executed'), ('TERMSHEET', 'Term Sheet')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence_text', models.TextField(blank=True, null=True)),
                ('is_match', models.BooleanField(default=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='reviews.review')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('EXTRACT', 'Extract'), ('EXPORT', 'Export'), ('VALIDATE', 'Validate')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('hash', models.CharField(blank=True, max_length=64, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='reviews.review')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
