# Generated by Django 5.2.8 on 2026-01-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractedterm',
            options={'ordering': ['source', 'key']},
        ),
        migrations.AddField(
            model_name='extractedterm',
            name='evidence_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='approved_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='executed_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='related_term_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='executed_file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='term_sheet_file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='extractedterm',
            name='source',
            field=models.CharField(choices=[('EXECUTED', 'Executed'), ('APPROVED', 'Approved'), ('TERMSHEET', 'Term Sheet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='code',
            field=models.CharField(choices=[('MISMATCH', 'Mismatch'), ('MULTIPLE_VALUES', 'Multiple Values'), ('MISSING_CLAUSE', 'Missing Clause'), ('CLAUSE_PRESENT', 'Clause Present'), ('COMPLETENESS', 'Completeness Check'), ('CONSISTENCY_FAIL', 'Consistency Failure')], max_length=30),
        ),
    ]
